name: exlib
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch=2.1
  - pytorch-cuda=12.1
  - torchaudio
  - torchvision
  - transformers
  - datasets
  - notebook
  - segment-anything=1.0
  - torchxrayvision=1.2.3
  - sentence
  - shap=0.43.0
  - lime=0.2.0.1
  - matplotlib=3.8.2
  - scikit-image
  - pip
  - pip:
    - git+https://github.com/fallcat/pytorch-grad-cam.git
  - bertopic
  - jsonlines
