name: exlib
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch-cuda=11.8
  - pytorch=2.1
  - torchaudio
  - torchvision
  - notebook
  - segmentation-models-pytorch=0.3.3
  - shap=0.43.0
  - lime=0.2.0.1
  - matplotlib=3.8.2
  - sckit-image
